config/routes.rb
Rails.application.routes.draw do
  root 'main#events'

  resources :menus
  get '/menu', to: 'menus#index', as: 'menus_path'
  get '/menu/new', to: 'menus#new'
  get '/functions', to: 'main#functions'
  get '/function_enquiry' => 'main#function_enquiry'
  post '/function_enquiry' => 'main#complete_function_enquiry', as: :functions_enquiries
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/menu.rb
class Menu < ApplicationRecord

  validates :name, :short_description, :long_description, :menu_type, presence: true
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  protect_from_forgery with: :exception
end

app/controllers/main_controller.rb
class MainController < ApplicationController

  def index
  end

  def events
    @title = 'Events'
  end

  def functions
    @title = 'Functions'
  end

  def privacy_policy
    @title = 'Privacy Policy'
  end

  def function_enquiry
    @title = 'Function Enquiry'
    @functions_enquiry = FunctionsEnquiryForm.new
  end

  def complete_function_enquiry
    @functions_enquiry = FunctionsEnquiryForm.new

    if @functions_enquiry.validate(params[:functions_enquiry])
      FunctionsEnquiryMailer.functions_enquiry_email(@functions_enquiry).deliver_now
      redirect_to :function_enquiry, notice: 'Your function enquiry has been submitted successfully'
    else
      render :function_enquiry
    end
  end
end

app/controllers/menus_controller.rb
class MenusController < ApplicationController

  def new
    @menu = Menu.new
  end

  def create
    @menu = Menu.new(menu_params)
    puts menu_params
    respond_to do |format|
      if @menu.save
        format.html { redirect_to menus_path, notice: 'Menu Item was successfully created.' }
        format.json { render :show, status: :created, location: @menu }
      else
        format.html { render :new }
        format.json { render json: @menu.errors, status: :unprocessable_entity }
      end
    end
  end

  def index
    @title = 'Menu'
    @menu = Menu.all
  end

  def show
    @menu = Menu.find(params[:id])
    respond_to do |format|
      format.html
      format.js
    end
  end

  def destroy
    @menu = Menu.find(params[:id])
    @menu.destroy
    respond_to do |format|
      format.html { redirect_to menus_path, notice: 'Recipe was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private

  def set_menu
    @menu = Menu.new
  end

  def menu_params
    params.require(:menu).permit(:name, :short_description, :long_description)
  end


end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/main_helper.rb
module MainHelper
end

app/views/layouts/application.haml
!!!
%html
  %head
    %meta{:content => 'text/html; charset=UTF-8', 'http-equiv' => 'Content-Type'}/
    %title Hansell & Gretel
    = csrf_meta_tags
    %meta{ :name => 'google-site-verification', :content => '_tUnXHnEM6--OZQGMEmmKduO949om1XfHzpIT-i1F40'}
    %meta{ :name => 'viewport', :content => 'width=device-width, initial-scale=1.0'}
    %meta{ :name => 'description', :content => 'Home of Gaythorne’s own espresso and breakfast bar!' }
    = stylesheet_link_tag    'application', media: 'all'
    = javascript_include_tag 'application'
  %body
    %p#menu-toggle
      Menu
    %div#blur{style: 'display: none'}
    %main
      =render 'components/header'
      %div.page_title__banner
        %h1.page__title
          =@title
      - flash.each do |key, value|
        %div.alert.alert-=value
      = yield
      =render 'components/footer'

app/views/main/events.haml
%section.events
  %h2.events__heading What's going on at Hansell & Gretel...
  %p.events__paragraph
    We host a varied range of events here at Hansell and Gretel. Events range from sit down degustation style feasts
    to monthly trivia to beer, wine and cooking classes. Check out what’s coming up soon below and be sure to like our
    Facebook page and subscribe to our events feed to be kept up to date!
  =render 'components/facebook_feed'

app/views/main/function_enquiry.haml
.enquiry__container
  .function-text
    %h1.menu__heading Book your next function with us!
    =image_tag('ornament.png', class: 'ornament')
    %div.row
      %div.container
        %p.events__paragraph
          We are excited to help you to host your event here at Hansell and Gretel! Please fill out the form below and
          our events team will be in touch with you as soon as possible to get your booking underway. Our packages are
          intended as a starting point - our Bar Manager and Executive Chef are more than happy to tailor your event to
          suit your requirements.
        = link_to 'More Information', functions_path, class: 'button'
      %span
      = image_tag 'group.jpg', class: 'enquiry__image'
.function_form__container
  %h1.menu__heading Get in Touch
  =image_tag('ornament.png', class: 'ornament')
  = form_for @functions_enquiry do |f|
    %fieldset.function__fieldset.test
      %div.function__field
        = f.label :date, 'Date of the Event'
        = f.text_field :date, type: :date, required: true
      %div.function__field
        = f.label :time, 'Time of the Event'
        = f.text_field :time, type: :time, required: true
      %div.function__field
        = f.label :occasion, 'Occasion'
        = f.text_field :occasion, required: true
      %div.function__field
        = f.label :name, 'Contact Person\'s Name'
        = f.text_field :name, required: true
      %div.function__field
        = f.label :email, 'Contact Person\'s Email'
        = f.text_field :email, required: true
      %div.function__field
        = f.label :phone, 'Contact Ph.'
        = f.text_field :phone, type: :phone, required: true
    %fieldset.function__fieldset
      %div.function__field
        = f.label :number, 'Number of Attendees'
        = f.text_field :number, type: :number, required: true
      %div.function__field
        = f.label :food_pkg, 'Food Package'
        = f.select :food_pkg, (['$39pp standing cocktail party package', '$39pp standing cocktail party package', '$49pp standing cocktail party package', '$59pp standing cocktail party package', '$45pp two course sit down package', '$55pp three course sit down package', '$65pp banquet package', 'Custom Package (We will be in touch to discuss your requirements)'])
      %div.function__field
        = f.label :drinks_pkg, 'Drinks Package'
        = f.select :drinks_pkg, (['* 2 hour basic beverage package $35pp *', '* 3 hour basic beverage package $45pp *', '* 2 hour spirits package $50pp *', '* 3 hour spirits package $60pp *', '2 hour premium wine package $55pp', '3 hour premium wine package $65pp', '2 hour premium wine and spirits package $70pp', '3 hour premium wine and spirits package $80pp', 'Custom Package (We will be in touch to discuss your requirements)'])
        %p.events__paragraph
          must purchase drinks package
      %div.function__field
        = f.label :exclusivity, 'Do you require exclusive use of the premises?', class: 'exclusivity'
      %section.checkbox__container
        %div
          %h1 Yes
          = f.radio_button :exclusivity, required: true
        %div
          %h1 No
          = f.radio_button :exclusivity, required: true
      = f.submit 'Submit', class: 'submit__button'

app/views/main/functions.haml
%section.functions
  =render partial: 'main/partials/functions_navigation'
  %div.functions__content.food_packages
    =link_to('Enquire Now', functions_enquiries_path, class: 'button')
    %h1.menu__heading--large
      Food Packages
    =image_tag('ornament.png', class: 'ornament')
    %h2.menu__subtitle
      All of our food packages include a glass of sparkling wine upon arrival for guests
    %div.row__container
      %div.row
        %div.functions__option
          %h1.menu__heading
            Standing Cocktail Party
          =image_tag('ornament.png', class: 'ornament')
          %h2.menu__subtitle
            Served over 2 hours
          %div.functions__item
            %p.row__paragraph
              %strong.row__paragraph--bold $39 pp
              including 6 savoury canapes (1.5 pieces of each item per person)
          %div.functions__item
            %p.row__paragraph
              %strong.row__paragraph--bold $49 pp
              including 6 savoury canapes and 2 sweet items (1.5 pieces of each item per person)
          %div.functions__item
            %p.row__paragraph
              %strong.row__paragraph--bold $59 pp
              including 6 savoury canapes, 2 sweet items & a noodle box ‘fork dish’ (1.5 pieces & 1 noodle box per person)
        =image_tag('steve_hansell_cooking.jpg', class: 'row__image')
      %div.row
        %div.functions__option
          %h1.menu__heading
            Sit Down Dinner
          =image_tag('ornament.png', class: 'ornament')
          %div.functions__item
            %p.row__paragraph
              %strong.row__paragraph--bold $45 pp
              Entree served ‘family-style’ as share platters for the table ω/ individually plated main course & salads for the table
          %div.functions__item
            %p.row__paragraph
              %strong.row__paragraph--bold $55 pp
              Entree served ‘family-style’ as share platters for the table ω/ individually plated main course, salads for the table & a selection of house-made sweet treats for dessert
        %div.functions__option
          %h1.menu__heading
            Banquet
          =image_tag('ornament.png', class: 'ornament')
          %div.functions__item
            %p.row__paragraph
              %strong.row__paragraph--bold $65 pp
              Buffet-style banquet including a selection of salads, wet dishes, breads & sweets
      =link_to('Enquire Now', functions_enquiries_path, class: 'button')
  %div.functions__content.drinks_packages
    =link_to('Enquire Now', functions_enquiries_path, class: 'button')
    %h1.menu__heading--large
      Drinks Packages
    =image_tag('ornament.png', class: 'ornament')
    %h2.menu__subtitle
      We offer a range of beverage package options for your convenience
    %div.row__container
      %div.row
        %div.functions__option
          %h1.menu__heading
            Pre-approved Bar Tab
          =image_tag('ornament.png', class: 'ornament')
          %div.functions__item
            %p.row__paragraph
              You decide how much you would like to spend and we will set your group up with a tab to that value.
              %br
                %br
                Our staff will monitor spending on the tab and inform you when you are reaching your pre-approved limit. We are able to extend this on the night if you wish.
        =image_tag('wine.jpg', class: 'row__image')
      %div.row
        %div.functions__option
          %h1.menu__heading
            Inclusive Packages
          =image_tag('ornament.png', class: 'ornament')
          %h2.menu__subtitle
            Available with the purchase of one of our
            =link_to('food packages', '#', class: 'event__paragraph')
          %div.functions__item
            %p.row__paragraph
              %strong.row__paragraph--bold Basic Package
              $35 pp over two hours or $45 pp over three hours
          %div.functions__item
            %p.row__paragraph
              %strong.row__paragraph--bold Spirits Package
              $50 pp over two hours or $60 pp over three hours
        %div.functions__option
          %h1.menu__heading
            Premium Drinks Only Package
          =image_tag('ornament.png', class: 'ornament')
          %div.functions__item
            %p.row__paragraph
              %strong.row__paragraph--bold Wine & Premium Beer
              $55 pp over two hours or $65 pp over 3 hours
          %div.functions__item
            %p.row__paragraph
              %strong.row__paragraph--bold Wine, Premium Beer & Spirits
              $70 pp over two hours or $80 pp over 3 hours
      %div.row
        =image_tag('glasses.jpg', class: 'row__image')
        %div.functions__option
          %h1.menu__heading
            Custom Package
          =image_tag('ornament.png', class: 'ornament')
          %div.functions__item
            %p.row__paragraph
              We are more than happy to discuss the possibilites of putting together a premium beverage package just for you and your group. Please do not hesitate to contact us with your requests
      =link_to('Enquire Now', functions_enquiries_path, class: 'button')

app/views/main/partials/_functions_navigation.haml
%ul.menu__navigation
  %li.menu__tab.menu__tab--active{:data => {:trigger => 'food_packages'}} Food Packages
  %li.menu__tab{:data => {:trigger => 'drinks_packages'}} Drinks Packages

app/views/menus/index.haml
=render partial: 'components/menu_banner', locals: {navigation: 'menus/partials/menu__navigation'}
%section.menu
  %div.breakfast{:data => {:content => 'breakfast'}}
    =render partial: 'menus/partials/breakfast', locals: { menu: @menu }
  %div.brunch
    =render partial: 'menus/partials/brunch', locals: { menu: @menu }
  %div.beverages
    =render partial: 'menus/partials/beverages', locals: { menu: @menu }

  

app/views/menus/index.js.erb
$('.menu').html("<%= j render partial: 'menus/partials/breakfast', locals: { menu: @menu } %>")

app/views/menus/new.haml
= form_for @menu do |f|
  - if @menu.errors.any?
    #error_explanation
      %h2
        = pluralize(menu.errors.count, "error")
        prohibited this item from being saved:
      %ul
        - menu.errors.full_messages.each do |message|
          %li= message
  .field
    = f.label :name
    = f.text_field :name
  .field
    = f.label :short_description
    = f.text_field :short_description
  .field
    = f.label :long_description
    = f.text_field :long_description
  .actions
    = f.submit 'Save Recipe', :class => 'submit green button'

app/views/menus/partials/_beverages.haml
%h1.menu__heading
  Beverages
=image_tag('ornament.png', class: 'ornament')
%div.row
  %div.functions__option
    %h1.menu__heading
      Coffee
    =image_tag('ornament.png', class: 'ornament')
    %h2.menu__subtitle
      Any coffee you can imagine just ask & we will present in our famous HnG way
    %ul
      %li.beverage__item
        %p.beverage__title
          Small(8oz)
        %p.beverage__price
          4
      %li.beverage__item
        %p.beverage__title
          Large(12oz)
        %p.beverage__price
          4.9
      %li.beverage__item
        %p.beverage__title
          Extra Large(16oz)
        %p.beverage__price
          5.9
      %li.beverage__item
        %p
      %li.beverage__item
        %p
      %li.beverage__item
        %p.beverage__title
          Extra Shot
        %p.beverage__price
          0.6
      %li.beverage__item
        %p.beverage__title
          Flavour Shot
        %p.beverage__price
          0.5
      %li.beverage__item
        %p.beverage__title
          Soy Milk
        %p.beverage__price
          0.6
      %li.beverage__item
        %p.beverage__title
          Mocha
        %p.beverage__price
          0.5
      %li.beverage__item
        %p.beverage__title
          Bubba-cino
        %p.beverage__price
          1.5
  %div.functions__option
    %h1.menu__heading
      House Specialty Coffee
    =image_tag('ornament.png', class: 'ornament')
    %h2.menu__subtitle
      All made with espresso as old school cappuccino...Yes there's froth
    %ul
      %li.beverage__item--bold
        %p.beverage__title
          Cup
        %p.beverage__price
          5
      %li.beverage__item--bold
        %p.beverage__title
          Mug
        %p.beverage__price
          6
      %li.beverage__item
        %p
      %li.beverage__item
        %p
      %li.beverage__item
        %p.beverage__title
          Extra Large(16oz)
        %p.beverage__price
          5.9
      %li.beverage__item
        %p.beverage__title
          Extra Shot
        %p.beverage__price
          0.6
      %li.beverage__item
        %p.beverage__title
          Flavour Shot
        %p.beverage__price
          0.5
%div.row
  %div.functions__option
    %h1.menu__heading
      Tea & Chai
    =image_tag('ornament.png', class: 'ornament')
    %h3.menu__heading--medium
      Tea
    %p.menu__subtitle--left
      Hansell & Gretel blend (black tea with hints of vanilla and caramel), Brisbane breakfast, Earl Grey, Russian Caravan, English Breakfast, Peppermint, Lemongrass & Ginger; Longjing Green
    %p.menu__price--centred
      Loose Leaf Tea by the Pot ...5
    %h3.menu__heading--medium
      Chai
    %p.menu__subtitle--left
      House made with real ground spices this is life changing
    %p.menu__price--centred
      By the Pot or Latte ...6.5
  %div.functions__option
    %h1.menu__heading
      House Specialty Hot Chocolate
    =image_tag('ornament.png', class: 'ornament')
    %h3.menu__heading--medium
      The Witches Brew
    %p.menu__subtitle--left
      Hansell has harnessed the Witch’s chocolate tear drops & combined them with the elixer of life! Thick enough to eat with a spoon or sip it slowly, we take this seriously!!
    %p.menu__price--centred
      $POA
%div.row
  %div.functions__option
    %h1.menu__heading
      Shakes, Smoothies and Frappes
    =image_tag('ornament.png', class: 'ornament')
    %h3.menu__heading--medium
      Smoothies
    %p.menu__subtitle--right
      (Ice-cream & milk) then pick your flavour….real banana, real blueberry, real raspberry, espresso, caramello, real strawberry, jaffa, macadamia, hazelnut or spinach
    %p.menu__price--centred
      $POA
    %h3.menu__heading--medium
      Frappes
    %p.menu__subtitle--right
      (yoghurt, honey & milk) then pick your flavour… banana, raspberry, blueberry, strawberry, kale or mixed berry...
    %p.menu__price--centred
      $POA
    %h3.menu__heading--medium
      Milkshakes
    %p.menu__subtitle--right
      (Ice-cream & milk) then pick your flavour….real banana, real blueberry, real raspberry, espresso, caramello, real strawberry, jaffa, macadamia, hazelnut or spinach
    %p.menu__price--centred
      $POA
    %ul
      %li.beverage__item
        %p.beverage__title
          Regular (16oz)
        %p.beverage__price
          7.5
      %li.beverage__item
        %p.beverage__title
          Kids
        %p.beverage__price
          4.5
  %div.functions__option
    %h1.menu__heading
      Soft Drink
    =image_tag('ornament.png', class: 'ornament')
    %p.menu__subtitle
      A changing selection of soda pop… check the drink fridge out inside……. Sarsparilla, Ginger Beer, Cherry Coke, Coke, L&P, Peachee, juices, American soda pop, water, lemonade, Creaming Soda, Aqua Frizzante (bubbly water)
%p.menu__disclaimer
  All our menus are subject to change at any time
  %br
  Additions we welcome, but sorry NO exchanges

app/views/menus/partials/_breakfast.haml
%h1.menu__heading
  Breakfast
=image_tag('ornament.png', class: 'ornament')
%h2.menu__subtitle
  7am - 11am
=render partial: 'menus/partials/display_menu', locals: { menu: @menu.select { |m| m.menu_type == 'breakfast' } }
%p.menu__disclaimer
  All our menus are subject to change at any time
  %br
  Additions we welcome, but sorry NO exchanges

app/views/menus/partials/_brunch.haml
%h1.menu__heading
  Brunch
=image_tag('ornament.png', class: 'ornament')
%h2.menu__subtitle
  11am - 2pm
=render partial: 'menus/partials/display_menu', locals: { menu: @menu.select { |m| m.menu_type == 'brunch' } }
%p.menu__disclaimer
  All our menus are subject to change at any time
  %br
  Additions we welcome, but sorry NO exchanges

app/views/menus/partials/_display_menu.haml
%div.column__container
  %div.column
    - menu[0...menu.length / 2].each do |n|
      %div.menu__item
        %h2.menu_item__name
          = n.name
        %p.menu_item__description
          = n.short_description
        %p.menu_item__long_description
          = n.long_description
  %div.column
    - menu[menu.length / 2 ... menu.length].each do |n|
      %div.menu__item
        %h2.menu_item__name
          = n.name
        %p.menu_item__description
          = n.short_description
        %p.menu_item__long_description
          = n.long_description

app/views/menus/partials/_menu__navigation.haml
%ul.menu__navigation
  %li.menu__tab.menu__tab--active{:data => {:trigger => 'breakfast'}} Breakfast
  %li.menu__tab{:data => {:trigger => 'brunch'}} Brunch
  %li.menu__tab{:data => {:trigger => 'beverages'}} Beverages